### ISSUE TITLE
patch stage provider need to block patch if patchSource is catalog but componentName is not specified

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#109]
In my understanding, if patchSource is catalog, provider will patch the config in catalog to the component in the solution where componentName matches. 

If we call provider with patchSource is catalog but componentName not specified, we will meet cast exception in [here](https://github.com/eclipse-symphony/symphony/blob/80a5ee0e2781672ecc2f8b27f9be2a25e9e8068d/api/pkg/apis/v1alpha1/providers/stage/patch/patch.go#L236). So maybe we'd better have a gateway [here ](https://github.com/eclipse-symphony/symphony/blob/80a5ee0e2781672ecc2f8b27f9be2a25e9e8068d/api/pkg/apis/v1alpha1/providers/stage/patch/patch.go#L165-L166) to block bad input.

@Haishi2016 Do you think if this is a valid fix?

**Comment by Haishi2016** [comment]
There are two ways of patching: 1) to add/remove/replace a component. In this case, componentName is not needed as it will be part of the component spec; 2) to modify specific property of a component. 

I agree we need to check for type cast exceptions in general, though.
