### ISSUE TITLE
k8sreporter fails to report target property since provisioningStatus is not set

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#138]
[k8sreporter](https://github.com/eclipse-symphony/symphony/blob/8c303a13a06888840be607e17af360b8f6701ab6/coa/pkg/apis/v1alpha2/providers/reporter/k8s/k8sreporter.go#L163C1-L165C6) is used to report properties for a target. 

However, as the provisioningStatus is marked as a required field in [k8s crd](https://github.com/eclipse-symphony/symphony/blob/8c303a13a06888840be607e17af360b8f6701ab6/k8s/config/oss/crd/bases/fabric.symphony_targets.yaml#L235-L236), the UpdateStatus call will fail since the provisioningStatus is not set.

        	Error Trace:	symphony/coa/pkg/apis/v1alpha2/providers/reporter/k8s/k8sreporter_test.go:97
        	Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Status.fabric.symphony \"a1\" is invalid: provisioningStatus: Required value", Reason:"Invalid", Details:(*v1.StatusDetails)(0xc0000dc000), Code:422}}
        	Test:       	TestInitWithMap

**Comment by Haishi2016** [comment]
Consider to decouple provisioningStatus from Symphony OSS object model. Also consider to split the bug into bug fix to make sure the exception doesn't happen, and splitting object model as enhancement.

**Comment by msftcoderdjw** [comment]
Assigned to @msftcoderdjw to evaluate if this issue can be resolved after merging codebase.
