### ISSUE TITLE
[Multi-site] Inconsistency between parent site id and CatalogSpec.SiteId fails remote provider

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#141]
When child site synchronizes catalogs from parent site, catalogs are named with {CatalogSpec.Siteid}-{CatalogSpec.Name}

However, remote provider, e.g. wait.go, materialize.go, make up catalog names using {Batch.Origin}-{CatalogSpec.Name}, where Batch.Origin is the siteid of parent site. 

When catalogs have a different CatalogSpec.SiteId from parent site id, remote provider will looks for the wrong catalog on the child site and obviously nothing can be found.

**Comment by Haishi2016** [comment]
We may consider to use ObjectMeta to distinguish/carry site info.
