### ISSUE TITLE
Add Github Action to build and publish images used by samples

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#168]
Here are the images that are needed for samples
| images | samples|
|--------------------|------------|
|sample-flask-app |docs/sample/canary <br> docs/samples/multisite <br> docs/samples/universe-data<br>docs/symphony-book/configuration-management |
|symphony-python-sdk| 	docs/samples/python-provider|
|symphony-akri| docs/symphony-book/akri|

**Comment by RemindD** [comment]
@Haishi2016 Shall we tag the new sample image with latest and overwrite the previous build or tag images with versions and keeps all the history?

**Comment by Haishi2016** [comment]
Let's just sync their versions with the main release version. This pipeline doesn't automatically bump the version numbers. And it's expected to run after the primary release has been created.
