### ISSUE TITLE
inputs in ActivationSpec should not be overwrite by inputs in StageSpec

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#183]
As I understand, inputs in StageSpec are default parameters for a stage to run and each time user can pass different inputs in activationSpec to change the values. However, currently stageSpec overrides ActivationSpec either from [code](https://github.com/eclipse-symphony/symphony/blob/552b73df72f794cb77026d5947a47e7ee2a583c1/api/pkg/apis/v1alpha1/managers/stage/stage-manager.go#L391C1-L399C4) or from experiment.

**Comment by msftcoderdjw** [comment]
@lirenjie95 to investigate and fix this issue.
