### ISSUE TITLE
Build Symphony binaries for ARM CPUs

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#199]
Symphony binaries work on ARM, but we don't have ARM build in the pipeline.

**Comment by msftcoderdjw** [comment]
Is this issue resolved by PR: #213 ? @Haishi2016

**Comment by msftcoderdjw** [comment]
Hi @Haishi2016 , I believe this issue should be resolved by PR #213 . So I closed this issue. Please feel free to reactivate if it is not finished.
