### ISSUE TITLE
Symphony automatically unwraps the first-level properties when creating configmap

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#202]
If a catalog has a complex type at root like  
complex_object:
    foo1: bar1
    foo2: bar2
The object is unwrapped and only foo1 and foo2 and sent to configmap. 
Desired behavior is that the properties are kept as they are.

**Comment by Haishi2016** [comment]
After discussion, the behavior would be if a property is post-fixed with "/*", we'll extract and return the properties under the property. Otherwise, the property is returned as is. Hence, in the above example, "complex_object/*" will return "foo1" and "foo2", while "complex_object" returns the object itself.

**Comment by msftcoderdjw** [comment]
Dup of #105

**Comment by msftcoderdjw** [comment]
Closed this as it dups to #105
