### ISSUE TITLE
State provider - In-memory state provider and Http state provider should use namespace and object name as the identifier

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#21]
(reported by @RemindD)

Previously, K8s state provider make CRUD operations on all symphony objects only in default namespaces which causes two issues:

If the symphony objects are actually created in a non-default k8s namespace, get operation failed
it cannot distinguish symphony objects in different namespaces with the same name
In recent changes, K8s state provider read namespace from Metadata and deal with the symphony object in the namespace passed in. In-memory state provider and Http state provider should also allow symphony objects with the same name in different namespaces.

**Comment by RemindD** [comment]
@Haishi2016 This has been fixed.

**Comment by msftcoderdjw** [comment]
Per @RemindD 's evaluation, closed this issue.
