### ISSUE TITLE
[Proposal] Support inheritance for nested properties in config provider

### ISSUE THREAD

**Issue by roopavidhya** [eclipse-symphony/symphony#210]
Ref - [symphony/docs/symphony-book/configuration-management/inheritance.md at main · eclipse-symphony/symphony (github.com)](https://github.com/eclipse-symphony/symphony/blob/main/docs/symphony-book/configuration-management/inheritance.md)

The config provider in symphony supports inheriting config values from a chain of parents. However, this is not supported for nested objects, Example - 

Config.yaml -

```
....
    wrapper:
        MySettings:
          Setting1: Value1FromSymphonyDev
....

```

Solution.yaml -

```
....
  env.MySettings__Setting1: "${{$config('lm-config', 'wrapper.MySettings.Setting1')}}"
....

```

throws the error - _Status - Details:  failed to evaluate deployment spec: field 'wrapper.MySettings.Setting1' is not found in configuration 'dev-config'_

**Expected behavior:**
 env.MySettings__Setting1 should be set to "Value1FromSymphonyDev".

**Comment by msftcoderdjw** [comment]
This feature is done in #398 .  How to use - https://github.com/eclipse-symphony/symphony/blob/main/docs/symphony-book/concepts/configuration_expressions.md#examples-of-usage.
