### ISSUE TITLE
Job manager is not reading Symhony objects outside of the default namespace

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#22]
(reported by @RemindD)

We have already fixed solutions, instances and targets in the previous issue. Need to fix other symphony objects - catalogs, device, campaign (stage), activation, staging, site, model, reference, security, skill, sync, user, trail.

**Comment by RemindD** [comment]
- catalogs.federation.symphony:
  - CRUD for non-default namespace
  - Catalog inheritance and override across different namespace
  - Cross site synchronization need to preserve the namespace of the catalogs
  - Graph Query GetChains and GetTrees for non-default namespace
  - EvaluationContext 
 - campaigns.workflow.symphony, activations.workflow.symphony
   - CRUD for non-default namespace
   - Cross-namespace workflow trigger (blocked?)
   - Cross site synchronization need to preserve the namespace of activation 
   - Stage providers need to respect the namespace of activation/campaign and access other symphony objects in the same namespace. e.g. set input['objectNamespace'] as namespace of activation 
https://github.com/eclipse-symphony/symphony/blob/65ad2d86ce9cacccaf0b5289b81d854bf6ebd055/api/pkg/apis/v1alpha1/providers/stage/list/list.go#L114-L116

**Comment by msftcoderdjw** [comment]
We need to check all in memory object to ensure namespace is populated and memory state provider also use namespace as part of primary key.

**Comment by msftcoderdjw** [comment]
Dup to #154 , removed this issue.
