### ISSUE TITLE
Show correct Activation status if campaign object is not found

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#24]
(reported by @RemindD)

Try the sample under ./docs/samples/campaigns/scheduled and reproduce using the following steps:

kubectl apply -f activation.yaml
kubectl apply -f campaign.yaml
kubectl get activation

Activation "scheduled-activation" is stuck with no status.
Check API logs and find an error indicating campaign object is not found in Activation workflow but no retries are attempted.

This issue could happen if activation resource is created before campaign resource.

Here are two questions:

Is it a valid scenario that activation resource is created before campaign resource, i.e. activate a campaign that may be created later
Shall we show Pausing in activation resource status if campaign resource is not found? Or a new status like "CampaignMissing"

(@Haishi2016)

Although we don't anticipate activation to be created without campaign, a better experience would be great. I think we can add validation hook that an activation object can only be created when the corresponding campaign is found.

(@msftcoderdjw)

Agree. Meanwhile, I found we don't have the dependency check when deleting symphony resources. One example is if we create instance which referenced a target. If we delete target at first, target deleting will succeed, but instance deletion is stuck.
image
Finally the instance will get deleted but seems cost more time.

**Comment by msftcoderdjw** [comment]
@RemindD is this issue covered by your validation check improvement effort?

**Comment by msftcoderdjw** [comment]
Fixed in https://github.com/eclipse-symphony/symphony/pull/302
