### ISSUE TITLE
Change ScheduleSpec to Datetime

### ISSUE THREAD

**Issue by FireDefend** [eclipse-symphony/symphony#259]
Hi team, do you think it is possible to use datetime type instead of ScheduleSpec? Arm team is suggesting us to change it.

type ScheduleSpec struct {
	Date string `json:"date"`
	Time string `json:"time"`
	Zone string `json:"zone"`
}

type StageSpec struct {
       ...
	Schedule        *ScheduleSpec        `json:"schedule,omitempty"`
}

-------

type StageSpec struct {
       ...
	Schedule        time.Time `json:"datetime"`
}

**Comment by Haishi2016** [comment]
Think of usability scenarios: Schedule a deployment at 5PM on Friday (local time).

**Comment by FireDefend** [comment]
OpenAPI spec is using ISO 8601. It will support offset date time(local time). I think we can use the same standard to parse in symphony code. https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by FireDefend** [comment]
fixed by the PR: https://github.com/eclipse-symphony/symphony/pull/276
