### ISSUE TITLE
Activation update should be blocked

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#271]
Once an activation is triggered and finished, it will be marked as succeeded. And it will not be triggered again with an update.

It can be quite perplexing for users when the campaign of the activation is altered, yet the status and output fields remain identical, potentially leading them to believe that a new campaign has been initiated and succeded.

**Comment by msftcoderdjw** [comment]
We agree we need to block the activation update since after execution it is a record.
