### ISSUE TITLE
Wait stage provider should not have endless wait

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#299]
If WaitCount is not set or set to 0, there would be endless loop calling API server to check if objects exist or not. And there is no way to stop the loop even if you delete campaign or activations. It only stops when API crashes.

This is not a good behavior. We should have a maximum WaitCount

**Comment by msftcoderdjw** [comment]
Since users may want to do the endless wait until cancellation, the better way to fix this issue is provide cancellation mechanism. Since activation is the event based system, we can leverage the contexnt.cancel in language side and do some self-checks in flow, or try new way, e.g. Actor framework,

**Comment by msftcoderdjw** [comment]
Short time: we decide to detect whether the activation is deleted when doing the wait. We try to achieve cancellation by deleting activation. And this should work on all stage providers.

**Comment by msftcoderdjw** [comment]
@lirenjie95 to evaluate this.
