### ISSUE TITLE
Pubsub subscriber should not return persistent error

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#306]
Pubsub will reclaim the event if the subscribe function failed to process it.

If the subscriber encounters persistent error like input is invalid, or dependent resource doesn't exist, it should persist the error message somewhere in the object rather than returning the error.

**Comment by msftcoderdjw** [comment]
E.g. 400 errors should abandon the event. We need to also revisit the error handling in symphony-api and add failfast for 400 error and report correct error code (shouldn't treat any errors as 500).
