### ISSUE TITLE
Resource creation and deletion should be blocked if condition is not met for dependency

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#307]
There are static reference and runtime reference in symphony.
Static reference means a fields under the Spec refer to another type of symphony objects. For example, Activations depend on campaigns. And Instances depend on solutions and targets.
runtime reference means the reference only takes effect at runtime. For example, solution can use $config to refer to a catalogs and the catalog is only used when the deployment happens on the solution.

We would like to block the creation of symphony objects if the dependency doesn't exist and also block the deletion of the dependency if the object that depends on it still exists.

**Comment by msftcoderdjw** [comment]
runtime reference means the reference only takes effect at runtime. For example, solution can use $config to refer to a catalogs and the catalog is only used when the deployment happens on the solution.

This problem will be tracked separately in issue #334

**Comment by msftcoderdjw** [comment]
I closed this issue since #396 has been merged. @RemindD please reopen it if this is not correct.
