### ISSUE TITLE
Clean up orphaned objects in state provider

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#312]
The following objects are only created but not deleted, might causing OOM or increase of db size.
- job heartbeat
- success time of an instance job
- success time of a target job
- success time of a deployment job
- solutionManagerDeploymentState - one per instance
- remote job status for multi-site - one per activation
- catalog synchronization status for multi-site - one per catalog

**Comment by msftcoderdjw** [comment]
deployment summary of an instance / target job

**Comment by msftcoderdjw** [comment]
We need to have a try for re-creation scenario.

**Comment by msftcoderdjw** [comment]
@LeiQL , please take a look at this issue.

**Comment by RemindD** [comment]
Hi, @msftcoderdjw . I think we only fixed part of the issue.
