### ISSUE TITLE
Removal of target object doesn't remove deployments on it

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#320]
Create instance, solution, target on symphony and solution deployment is trigger. If target is deleted while instance and solution remain there, instance status does show the target count drops to 0.
```
NAME                          STATUS      TARGETS   DEPLOYED
sampleprometheusinstance-v1   Succeeded   0         0
```
However, the deployment remains there.
The issue happens in both case when instance specifies target name or target selector.

**Comment by msftcoderdjw** [comment]
This issue was fixed in #325
