### ISSUE TITLE
Validation missing for campaign

### ISSUE THREAD

**Issue by lirenjie95** [eclipse-symphony/symphony#321]
Scenario 1
* Create campaign with three stages `["approval", "deploy", "end"]`, and the firstStage is `"foo"`
    * Result:
    * Creation is successful
    * Create an activation to trigger that campaign
    * The campaign will run but nothing will happen
* Expect: return an error message

Scenario 2
* Create campaign with an empty list stages, and the firstStage is empty
    * Result:
    * Creation is successful
    * Create an activation to trigger that campaign
    * The campaign will run but nothing will happen
* Expect: Creation should return an error message

**Root cause: validation missing when creating the campaign. Didn't check if the firstStage in the stages list.**

[not finished yet, will update more scenarios later.]

**Comment by msftcoderdjw** [comment]
Assign to @RemindD , we need to block the firstStage which is not in the list. We need to block empty firstStage.
