### ISSUE TITLE
Catalog using ParentName should fail if parent catalog doesn't exist

### ISSUE THREAD

**Issue by iwangjintian** [eclipse-symphony/symphony#322]

**Comment by RemindD** [comment]
Also fail the case when parent catalogs make up a loop

**Comment by msftcoderdjw** [comment]
Wrong parent name (loop or not exist) will be checked in creation. Assign to @RemindD .

**Comment by lirenjie95** [comment]
Scenario: Catalog reference makes a loop
* Set two catalog files: in catalog A, it should contain a field that refers to catalog B's field; and in the catalog B's same field, it refers back to catalog A (**NOT SURE**: maybe it should be in a single catalog file, but the reference loop is for two fields)
* EXPECT: the creation will fail and tell the user that there is a reference loop.
* RESULT: the campaign will be stuck in "Running" Status (infinite loop)

**Comment by msftcoderdjw** [comment]
@iwangjintian works with @linyguo to fix this.

**Comment by msftcoderdjw** [comment]
Will be fixed in PR #396 by @RemindD
