### ISSUE TITLE
Catalog specifying parent name should be checked with circular dependency

### ISSUE THREAD

**Issue by iwangjintian** [eclipse-symphony/symphony#333]
we should check the inherit circle during create and update

**Comment by msftcoderdjw** [comment]
Assigned to @RemindD , please fix this issue in your strengthen validation work.

**Comment by msftcoderdjw** [comment]
@iwangjintian works with @linyguo to fix this.

**Comment by linyguo** [comment]
Fixed in https://github.com/eclipse-symphony/symphony/pull/453
