### ISSUE TITLE
Campaign > http stage :  body input is not passed to http request

### ISSUE THREAD

**Issue by robertslessor** [eclipse-symphony/symphony#345]
When using an Http stage as part of a campaign, if the body is specified as one of the inputs, its value is not then passed to the http provider.  This means that the http request is sent without containing the properties passed. 

An example of this is when creating a POST to LogicApp as part of an approval stage in a campaign. Information such as instance, solution and target is not sent to the LogicApp be included as part of the email.

![image](https://github.com/eclipse-symphony/symphony/assets/87993148/139909dd-dc4a-4c74-bb1a-4314cbb3347b)

Version Seen: [0.48.25](https://github.com/eclipse-symphony/symphony/tree/0.48.25)

**Comment by msftcoderdjw** [comment]
@lirenjie95 please have a test on this.
