### ISSUE TITLE
We are still forbidding names to contain hyphens 

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#346]
https://github.com/eclipse-symphony/symphony/blob/f67d3108fd3ade6b13ad3cf3f0afcf23063f0c52/k8s/configutils/configutil.go#L123

There's no reason for having this constraint

**Comment by msftcoderdjw** [comment]
We have new constraints for -v-. But the commit here doesn't align with main branch. We have permitted using - as hyphen in resource name. @LeiQL to confirm.

**Comment by LeiQL** [comment]
@Haishi2016  the constraint is not in main branch.

**Comment by msftcoderdjw** [comment]
False alarm.
