### ISSUE TITLE
Activation can't trigger the second stage of a campaign

### ISSUE THREAD

**Issue by lirenjie95** [eclipse-symphony/symphony#347]
Activation triggers campaign from a stage which is not firstStage
* Create campaign with two stages `["first", "second", "third"]`, firstStage is `"first"`, and selfDriving is false
* stage provides are all mocks
* Get campaign, check campaign properties is expected
* Create Activation triggers campaign (from the first stage, input is null)
* The activation will trigger the first stage and become `"Done"`
* Create Activation triggers campaign (from the second stage, input is null)
* Wait until Activation status is DONE and check activation output
    * Expect: The creation will succeed, and will trigger the second stage of the campaign
    * Result: The activation will stuck. In the Status, the stage is still the first stage.

Could be a easy fix here:
https://github.com/eclipse-symphony/symphony/blob/main/k8s/controllers/workflow/activation_controller.go#L67

**Comment by msftcoderdjw** [comment]
@RemindD will fix this.

**Comment by msftcoderdjw** [comment]
Fixed in https://github.com/eclipse-symphony/symphony/pull/354.
