### ISSUE TITLE
creation of an activation that trigger an NOT existing campaign stage (error path)

### ISSUE THREAD

**Issue by lirenjie95** [eclipse-symphony/symphony#349]
Scenario: activation trigger an NOT existing campaign stage
* Create campaign with two stages `["first", "second", "third"]`, firstStage is `"first"`, and selfDriving is false
* stage provides are all mocks
* Get campaign, check campaign properties is expected
* Create Activation triggers campaign (from the stage `"notExist"`, input is null)
* Expect: the creation will fail
* Result: 
    * stage is `"notExist"` (As expected)
    * the creation is successful, in the the status field, the stage is the first stage of the campaign (Not as expected)

**Comment by msftcoderdjw** [comment]
We will block the activation creation if the stage is not valid in webhook. Covered by the validation improvements by @RemindD .
