### ISSUE TITLE
stageSelector pointed to an non-existed campaign stage, but the creation will still be successful

### ISSUE THREAD

**Issue by lirenjie95** [eclipse-symphony/symphony#351]
Scenario: stageSelector pointed to an non-existed campaign stage(error path)
* Create campaign with two stages ["first", "second"] with selfDriving is true
* for the "first" stage, set the stageSelector to be "third"
* stage provides are all mocks
* Expect: an error shows that the stageSelector's value is invalid. Creation is failed.
* Result: creation is successful

**Comment by msftcoderdjw** [comment]
Covered by @RemindD 's validation improvements.
