### ISSUE TITLE
If Ingress Provider is necessary? Ingress update is frozen now. 

### ISSUE THREAD

**Issue by yanjiaxin534** [eclipse-symphony/symphony#353]
In K8S [ingress doc](https://kubernetes.io/docs/concepts/services-networking/ingress/). Ingress update is frozen now. I don't know if ingress is a necessary provider? If it will be deprecated in the future, I will not write test case for ingress.

**Comment by msftcoderdjw** [comment]
We will still support ingress provider before we have any new target providers such as Gateway API. If K8S deprecates ingress, we can deprecate ingress provider. Before that, we still need to test it since it is critical for canary deployment.
