### ISSUE TITLE
Redis pubsub support multiple subscriber for one publisher

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#358]
In https://github.com/eclipse-symphony/symphony/pull/339, all the consumer groups are using constant value RedisGroup = "symphony". As a result, if there are multiple subscribers for the same topic, they will compete for messages. 

The fix is to set different consumer groups for different subscribers so that every message published to the topic can be processed by all subscribers. A simple idea is to change Subscribe interface to pass in a number. Note that the number should be deterministic so different symphony replicas will use the same consumer group.

**Comment by msftcoderdjw** [comment]
Current pubsub is implemented for one publisher and one subscriber (so the consumer group is fixed value). Only trail case is using multiple subscriber now. Considering future case, we need to fix this to pass consumer group.
