### ISSUE TITLE
config parsing failed: due to setting namespace missing in stage-manager.go

### ISSUE THREAD

**Issue by lirenjie95** [eclipse-symphony/symphony#364]
Scenario:
* Create a catalog container
* Create a catalog version whose root Resource is the container
    * in the specs : properties field, set name to be "root"
* Create a campaign container
* Create a campaign version
    * have two stages, all are mock
    * in the second stage, one input is "name": "${{$config(catalog11:v1,name)}}"
* Create an activation to trigger the campaign version
* Result:
    * activation failed and shows "unexpected end of JSON input"
    * in the api logs, shows that "caused by: catalogs.federation.symphony \"catalog11-v1\" not found"
    * deploy a catalog version under default namespace and create an activation again, it will run successfully
* Root cause: setting namespace operation is missing in `stage-manager.go`. The integration tests only cover the solution (the setting namespace operation is present in `solution-manager.go`) so we didn't find it before.

**Comment by msftcoderdjw** [comment]
Missing namespace when initing eval context in campaign / activation. expression parsing in campaign / activation in non-default namespace will fail.

**Comment by msftcoderdjw** [comment]
Re-assign to @linyguo
