### ISSUE TITLE
Create stage provider doesn't set the namespace in requestBody

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#384]
The namespace of the object created in create stage provider should respects the following order the same as materialize stage provider
1. input["objectNamespace"]   -> specified in campaign stage spec
2. input["__namespace"]  -> set at runtime, same as campaign namespace

Then we need to set the namespace explicitly in the requestBody of create call.

Currently we takes input["object"] directly which is not correct.
https://github.com/eclipse-symphony/symphony/blob/09a6a5979abbf22418704534c9e3811a49ffb520/api/pkg/apis/v1alpha1/providers/stage/create/create.go#L134C2-L138C3

**Comment by msftcoderdjw** [comment]
Namespace in request body.
Namespace in campaign / activation.

Follow the logic in materialize provider.

**Comment by msftcoderdjw** [comment]
Assign to @lirenjie95
