### ISSUE TITLE
script target provider bug

### ISSUE THREAD

**Issue by yanjiaxin534** [eclipse-symphony/symphony#391]
output file cannot generate. So error is ::""  P (Script Target): failed to parse apply script output (expected map[string]model.ComponentResultSpec): open home/7ee6cdb4-b12c-4af4-a736-8be4bcd2d46b-output.json: no such file or directory" instance=symphony-api-85cf46d654-4qpkn scope=providers.target.script type=log ver=unknown"

**Comment by msftcoderdjw** [comment]
Doc issue.
