### ISSUE TITLE
Evaluation error in soltuion deployment is not clear

### ISSUE THREAD

**Issue by msftcoderdjw** [eclipse-symphony/symphony#416]
e.g. when catalog version reference is wrong.

Instance status shows, (no clear catalog version)
Deployment failed. failed to evaluate deployment spec: Not Found: object not found

**Comment by msftcoderdjw** [comment]
Assigned to @linyguo

**Comment by linyguo** [comment]
Link related issue: https://github.com/eclipse-symphony/symphony/issues/492
