### ISSUE TITLE
 $config value not parsed in parent attribute

### ISSUE THREAD

**Issue by linyguo** [eclipse-symphony/symphony#420]
Repo:
In Solution.yaml:
  container.image: "${{$config('config1:v1','image')}}"

In config1.yaml:
  parentName: config2-v-v1
  properties:
    image2: "${{$config('config2:v1','image')}}"

In config2.yaml:
  properties:
    image: "${{$config('config1:v1','image2')}}"

After deployed, pod output:
Events:
  Type     Reason         Age                   From               Message
  ----     ------         ----                  ----               -------
  Normal   Scheduled      2m15s                 default-scheduler  Successfully assigned k8s-scope/instance03-84cd6ccdd-g77zw to minikube
  Warning  InspectFailed  12s (x11 over 2m14s)  kubelet            Failed to apply default image tag "${{$config('config1:v1','image2')}}": couldn't parse image name "${{$config('config1:v1','image2')}}": invalid reference format
  Warning  Failed         12s (x11 over 2m14s)  kubelet            Error: InvalidImageName
![image](https://github.com/user-attachments/assets/1ade1878-8d4b-4af8-9e63-8b6aca5eae53)

**Comment by msftcoderdjw** [comment]
We will fix and support this scenario.

**Comment by linyguo** [comment]
Fixed, can close this bug now
