### ISSUE TITLE
doc link for a symphony agent json file without K8s is incorrect 

### ISSUE THREAD

**Issue by cicorias** [eclipse-symphony/symphony#482]
The link here : [docs/symphony-book/agent/polling-agent.md?plain=1#L16](https://github.com/eclipse-symphony/symphony/blob/0a317edbe8fcced2c22e13a9a8708888ad0aff00/docs/symphony-book/agent/polling-agent.md?plain=1#L16) unfortunately does to a different file name called [(../../../api/symphony-k8s-poll-agent.json)](https://github.com/eclipse-symphony/symphony/blob/main/api/symphony-k8s-poll-agent.json)

Ideally there is a sample or version that is NOT k8 as the link indicates or perhaps correct the documentation.

**Comment by Haishi2016** [comment]
Will be addressed by https://github.com/eclipse-symphony/symphony/pull/509
