### ISSUE TITLE
script provider does not recognize component result status code

### ISSUE THREAD

**Issue by linyguo** [eclipse-symphony/symphony#521]
For script provider, script generates output file which contains a map of component results, the status codes are as follows
- 8001: fialed to update
- 8002: failed to delete
- 8003: failed to validate component artifact
- 8004: updated (success)
- 8005: deleted (success)
- 9998: untouched - no actions are taken/necessary

However, current script provider handles only script execution error (eg. when exit code is nonzero). If the script executes complete, it will not return error. We should consider to improve the user experience to either respect component status code or handle return code based on component result.

![image](https://github.com/user-attachments/assets/46b718dc-d772-4938-9d57-339e9a5df7b7)

**Comment by msftcoderdjw** [comment]
Script target provider doesn't handle the failure status code in script output file, and only judge the return code. We need to fix it.
