### ISSUE TITLE
delayed job event continuously publish new jobs

### ISSUE THREAD

**Issue by linyguo** [eclipse-symphony/symphony#550]
When a job is delayed, a new job is published:
![image](https://github.com/user-attachments/assets/18fd56da-6f25-4122-a4a8-222ee604c05a)
We should consider adding a time interval for the job publish, otherwise it will continuously publish the job

**Comment by msftcoderdjw** [comment]
At least we need to implement exponential backoff in retry.

**Comment by msftcoderdjw** [comment]
Evaluate if we can avoid ack this message and keep this message in pubsub instead of republish this event. (This could help to reduce the duplicated event.)

**Comment by linyguo** [comment]
https://github.com/eclipse-symphony/symphony/pull/572 is a temporary mitigation for this issue
