### ISSUE TITLE
Unreachable code in create stage provider

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#564]
https://github.com/eclipse-symphony/symphony/blob/ccf7804b126ae531a3c6e5afb686743b0b2e004d/api/pkg/apis/v1alpha1/providers/stage/create/create.go#L327C3-L327C4

**Comment by msftcoderdjw** [comment]
@linyguo is aware of this issue, and she is working on a fix in this PR: https://github.com/eclipse-symphony/symphony/pull/568, together with other changes.
