### ISSUE TITLE
Remove baseUrl, user, password settings 

### ISSUE THREAD

**Issue by Haishi2016** [eclipse-symphony/symphony#57]
There are few places that baseUrl, user, and password are treated as settings to connect to Symphony API. We need a better way to handle this. Especially, we need to get rid of the user/password settings.

**Comment by msftcoderdjw** [comment]
We provided service account token when deploying in k8s. I believe this issue has been fixed. @iwangjintian to evaluate.

**Comment by iwangjintian** [comment]
We've removed almost all the usage of user/password but the multisite syncing.

**Comment by msftcoderdjw** [comment]
Thanks for evaluation. @iwangjintian Given this work is done in major path. I think we could close this issue. @Haishi2016  please feel free to reactivate if you have any concerns.
