### ISSUE TITLE
Running maestro up in WSL sometimes failed due to "Error: error getting credentials - err: fork/exec /usr/biin/docker-credential-desktop.exe: exec format error, out: ``"

### ISSUE THREAD

**Issue by msftcoderdjw** [eclipse-symphony/symphony#71]
![image](https://github.com/eclipse-symphony/symphony/assets/59427055/f35a6e24-9a5d-45fb-8fee-2be4e6bf888c)

**Comment by msftcoderdjw** [comment]
About this issue,
1. Current maesto CLI doesn't print any error logs so users cannot know how to diagnose this issue.
2. We need to add the mitigations in the doc: https://forums.docker.com/t/docker-credential-desktop-exe-executable-file-not-found-in-path-using-wsl2/100225 - Delete the line with credsStore from ~/.docker/config.json.

**Comment by Haishi2016** [comment]
if you do maestro up --verbose you can see detailed outputs

**Comment by msftcoderdjw** [comment]
Thanks for the hints, @Haishi2016 . I have tried verbose logs, seems it prints too much information. Do you think if it is feasible we can print errorOutput even users don't enable --verbose?
