### ISSUE TITLE
[Multi-site] Activation triggers a stage on remote sites causing symphony to crash

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#8]
In stage-vendor.go, parent sites relay on the status.Output["__campaign"] from child site's response to decide in which campaign the next stage need to run. However, the Output["__campaign"] field is not set at child site side which causes unhandled string cast exception.

stack trace:
panic: interface conversion: interface {} is nil, not string

goroutine 33 [running]:
github.com/azure/symphony/api/pkg/apis/v1alpha1/vendors.(*StageVendor).Init.func3({0xc00078c820?, 0x4e?}, {0x0, {0x1f98a20, 0xc0007a0090}})
	/workspace/api/pkg/apis/v1alpha1/vendors/stage-vendor.go:187 +0x774
...

**Comment by Haishi2016** [comment]
Hi @RemindD, can you please provide a simple campaign definition to recreate the problem?

**Comment by RemindD** [comment]
Hi, @Haishi2016 . This can be reproduced when run examples under docs/samples/multisite.

1. Deploy a symphony on AKS (parent site). Also, another symphony deployed locally in my WSL (child site) and configure the AKS symphony as its parent. 
2. Apply instance-catalog.yaml, solution-catalog.yaml and target-catalog.yaml on AKS symphony. The catalog objects will be first observed on parent site and then be synchronized to child site.
3. Apply Campaign on AKS symphony and then activation object to trigger the campaign. 
I notice the activation object get stuck at 9995 paused state and symphony on parent site crashed due to this issue. The root cause of this issue is parent site expect several fields (campaign, activation name, etc.) set on the response however child site doesn't set them.
I have a proposed fix and will send out a PR today.
