### ISSUE TITLE
Vendors doesn't make sure id and spec.Name is the same

### ISSUE THREAD

**Issue by iwangjintian** [eclipse-symphony/symphony#83]
https://github.com/eclipse-symphony/symphony/blob/50a91b7fe8586e015b86bda2e1666b5d2a13ca11/api/pkg/apis/v1alpha1/vendors/catalogs-vendor.go#L263

And this seems to be a general issue

**Comment by msftcoderdjw** [comment]
Seems we don't have name property in spec. @iwangjintian , please confirm whether this issue still there.
