### ISSUE TITLE
K8s state provider update status uses wrong json structure

### ISSUE THREAD

**Issue by RemindD** [eclipse-symphony/symphony#90]
1. k8s state provider uses wrong json structure and K8s complains provisionStatus field not found. need to construct status.properties rather than status.status.properties. 

https://github.com/eclipse-symphony/symphony/blob/9c6be107f88421af36e736192e991fc4a3d8a6fc/api/pkg/apis/v1alpha1/providers/states/k8s/k8s.go#L247C1-L253C43

2. After a second thought, currently k8s controller update target status using k8s client directly rather than send an onStatus rest call to symphony core target vendor. That's why it's not captured on K8s scenario. @Haishi2016 I think that's not a good practice maybe it's better to let k8s controller to call symphony core to update target status.

**Comment by Haishi2016** [comment]
I think sending to onStatus is likely to cause a ping-pong effect because k8s controller reacts to status change as well.

**Comment by RemindD** [comment]
This is by design. Close as not a bug.
